#' Import a .parquet file and convert it to a .tsv file.
#' 
#' @description Takes the `report.parquet` generated from DIA-NN version 1.9 and above and creates a report.tsv file. This helps people to more easily browse their data using Excel.
#' 
#' @param ParquetFileName The file path and name of the main `report.parquet` file generated by DIA-NN. By default, this will use the file name given by DIA-NN "report.parquet" in your active directory. If an argument is entered, it should be a string.
#' @param TsvFileName The desired name of the exported tsv report. Should be a string and end in `.tsv`
#' 
#' @return A tsv file written into your active directory with the same name as the one entered for `FilePath`. By default, this will be `report.tsv`. If an argument is entered, it should be a string.
#' @export
#' 
convert_parquet <- function(ParquetFileName = 'report.parquet',
                            TsvFileName = 'report.tsv') {
  
  message('[1/2] Loading the data from the parquet file...
          
          ',
          appendLF = FALSE)
  
  parquet_report <- arrow::read_parquet(ParquetFileName)
  
  message('[2/2] Writing the data to a tsv file...
          
          ',
          appendLF = FALSE)
  
  readr::write_tsv(parquet_report,
                   TsvFileName)
}